apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: datastore
  resources:
    requests:
      storage: 5Gi
