apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-chrome-demo

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: vnc-pw
        image: 490516395361.dkr.ecr.eu-west-2.amazonaws.com/chrome-test:latest
        imagePullPolicy: Always
        name: chrome-demo
        ports:
        - containerPort: 6901
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/kasm-user/.config/google-chrome/Default
          name: chrome-demo-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: chrome-demo-data
        persistentVolumeClaim:
          claimName: chrome-efs-claim
